### ISSUE TITLE
UI Labels not showing correctly

### ISSUE THREAD

**Issue by iMuMz** [64robots/nova-fields#100]
Laravel 5.8
Laravel Nova 2.0.3
64robots/nova-fields 0.8.7

The labels for the repeating fields do not seem to display correctly with version 0.8.7

If I switch to an earlier version of nova fields, the labels display correctly.

![Screenshot 2019-06-07 at 10 00 24](https://user-images.githubusercontent.com/22936672/59090136-326b0c80-890c-11e9-818d-cc618c4bae32.png)

**Comment by disitec** [comment]
Yeah sorry. This is an intended undocumented change. Working on docs in another branch.

Now, for coherence, heading classes are pulled from field `wrapperClasses` instead of field `fieldClasses`. In addition same classes as `deleteButtonClasses` are propagatted down in order to create a required space at the end.

You can see the changes here
https://github.com/64robots/nova-fields/commit/6f7d52358785f01c5777a6bba928f990721c41a9

You should adjust your Row `headingClasses` for the wrapper and each field `wrapperClasses`.

Sorry about that. Let me know if it helps.
