### ISSUE TITLE
Row fieldclasses unclear

### ISSUE THREAD

**Issue by Jebble** [64robots/nova-fields#174]
Hi there,

I'm using the Row field quite often but for some reason whatever I try to change
i.e. childConfig / wrapperClasses / fieldClasses etc. I don't see anything happen and it's very unclear form the documentation which method is meant for which classes.

Would it be possible to get a clearer picture in the documentation what all these methos for the Row field do?

**Comment by malinowskip** [comment]
It looks like row wrappers are actually using `itemWrapperClasses`, and individual items don't have wrappers at all (they are just plain paragraphs, unless the field is a `File` or `Boolean` field), if I understand the source and docs correctly.

Below, in the Vue component, the `div` looks like a row wrapper (because it wraps all items in a given row), but it uses `itemWrapperClasses`
```vue
// resources/js/components/row/DetailField.vue

<div
  v-for="row in values"
  :key="row.row_id"
  :class="field.itemWrapperClasses"
>
  <DetailFieldItem
  // ...
  />
```

There are some default classes defined in the `Row` nova field:
```php
// src/Row.php

public $rowWrapperClasses = 'flex items-center border-40 border relative';
```
But they don't seem to be rendered anywhere.

Field items don't seem to have wrappers at all (they are paragraphs), unless they are `Boolean` or `File` fields:
```vue
// resources/js/components/row/DetailFieldItem.vue

<template>
  <div
    v-if="isBoolean"
    class="text-center"
    :class="fieldClass"
  >
    <span
      class="inline-block rounded-full w-2 h-2 mr-1"
      :class="statusClass"
    />
  </div>
  <detail-nova-fields-file
    v-else-if="isFile"
    :value="display"
    v-bind="{ ...$props }"
  />
  <p
    v-else
    :class="fieldClass"
  >{{ display }}</p>
</template>
```

**Comment by malinowskip** [comment]
Ok, I just realized that `rowWrapperClasses` are used in form views (creating/updating a model), while `itemWrapperClasses` are used in detail views. In any case, I think this could be made clearer in the documentation.

**Comment by beliolfa** [comment]
Thank you @malinowskip will merge!
