### ISSUE TITLE
[Feature]Allow to append, not only override css classes

### ISSUE THREAD

**Issue by bernhardh** [64robots/nova-fields#8]
Let's say we have a textarea and want to add a css class, to shrink it:

```php
\R64\NovaFields\Textarea::make("Öffnungszeiten", "opening_hours")
    ->inputClasses('height-75'),
```

where `height-75` is a custom css class.  But this will destroy the default layout, because it overwrites the default classe so you have to use everywhere:

```php
\R64\NovaFields\Textarea::make("Öffnungszeiten", "opening_hours")
    ->inputClasses("w-full form-control form-input form-input-bordered py-3 min-h-textarea height-75"),
```

which is not really userfriendly, since you always have to look for the current css classes, have to maintain changes to these classes, etc.

Maybe add a second boolean option the the *Classes methods (inputClasses, labelClasses, etc.) do decide, if we want to append or override the default classes. Something like this:

```php
// Same behavior like now: Overwrite it
\R64\NovaFields\Textarea::make("Öffnungszeiten", "opening_hours")
    ->inputClasses('height-75'),
// Will append, instead of overwrite
\R64\NovaFields\Textarea::make("Öffnungszeiten", "opening_hours")
    ->inputClasses('height-75', false),
```

**Comment by ragingdave** [comment]
I would totally advocate for add* type methods rather than a cryptic Boolean tacked on

**Comment by bernhardh** [comment]
I could live with that, but in my eyes, its just splitting hairs. 

The current method is just manipulating the css classes of the fields. At the moment, you don't know if it appends or if it overwrites. So to make it not "cryptic", you would have to change these method names as well to "changeInputClass, changeLabelClass", etc. (or updateLabelClass, etc.). So you would not only double the methods, but you would also break current behaviour.

**Comment by disitec** [comment]
Sounds good to me. I’ll take a look on this and think in the best api.

**Comment by ragingdave** [comment]
I only advocated for clarity since, a setter (inputClasses) and an adder (addInputClass) just seem more straight forward to someone reading the code. Rather than having to hit up documentation (which at the moment doesn't really exist, not blaming anyone), the clear and readable separation of changing the class vs adding a class is clear. Additionally there is already at least one example of this kind of thing in laravel already. For example in the query builder there is select (replacing the current selects) and addSelect ( just adding a new select). I don't think we would need to actually change much of the current names and still end up in a clear functionality description.

**Comment by disitec** [comment]
Added the following methods to 0.3.0:

* addInputClasses
* addWrapperClasses
* addFieldClasses
* addPanelFieldClasses
* addLabelClasses
* addPanelLabelClasses
* addExcerptClasses
